version: "3"
services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ${APPLICATION}:/var/www/html
      - ${SSLPATH}:/var/www/ssl-rootCA
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    links:
      - php-fpm
    networks:
      code-network:
        ipv4_address: 172.18.0.4

  php-fpm:
    container_name: php-fpm
    restart: always
    build:
      context: ./php-fpm
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ${APPLICATION}:/var/www/html
      - ${SSLPATH}:/var/www/ssl-rootCA
      - ${CLIPATH}:/var/www/cli
    expose:
      - "9000"
    networks:
      code-network:
        ipv4_address: 172.18.0.3

  mysql:
    container_name: mysql
    restart: always
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      code-network:
        ipv4_address: 172.18.0.2

networks:
  code-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
